# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf4d51a725af3707e19cc2624c5df341be2c7f9c66ce06b8783e7302eafd2d92aa2a083236184eafcb2ef50bece4d4572ec465deb8b5042fdb58d43ad263dd5

test:
  secret_key_base: b1b67d03cd540991801b1ba006bf2606e54707ba694bb700eabcd59733dd4d417f36779b63a188726ca6be7d7f2e2fcbfb540e8a7f89e9c8d78017859254c7f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
