# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d9d2a3265c303c806a8665aa513c4110ea94fac09cf9cc6dceff8a75b33e1e27ff9e66f66bd3a5a89f70272bf97baa213bff18890290c6f8eff9be08b0eed32

test:
  secret_key_base: d55d721ccda1a6bcec0537a7eb15fc8598a0d6089b623a225203e6dedd85b0b0f90a73fb814c074c6af0fb68cc183c53e988326b0ddf3ccb26ba8b40621403e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
